apiVersion: v1
kind: Service
metadata:
  name: {{ include "redstone-mud.fullname" . }}
  labels:
    {{- include "redstone-mud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- range .Values.additionalPorts }}
    - port: {{ .containerPort }}
      targetPort: {{ .name}}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "redstone-mud.selectorLabels" . | nindent 4 }}
