{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rs-service.fullname" . }}
  labels:
    {{- include "rs-service.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ include "rs-service.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
        {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "rs-service.fullname" $ }}
                port:
                  number: {{ include "rs-service.servicePort" (list $.Values.service $) }}
        {{- end }}
{{- end }} 