{{- if .Values.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rs-service.fullname" . }}-env
  labels:
    {{- include "rs-service.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
