{{/*
Service for single common
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ include "common.servicePort" (list .Values.service .) }}
      targetPort: {{ include "common.targetPort" (list .Values.service .) }}
      protocol: TCP
      name: http
    {{- if and .Values.grpc .Values.grpc.enabled }}
    - port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
      protocol: TCP
      name: grpc
    {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}