apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graph-node.fullname" . }}-config
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
data:
  graph-node.toml: {{ toYaml .Values.config.file | indent 2 }}