{{- if .Values.frontend.enabled }}
{{- if .Values.frontend.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autoscout.fullname" . }}-frontend-env
  labels:
    {{- include "autoscout.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.frontend.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}