apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dshackle.fullname" . }}-config
  labels:
    {{- include "dshackle.labels" . | nindent 4 }}
data:
  dshackle.yaml: |-
    version: v1
    port: {{ .Values.service.grpcPort }}
    host: 0.0.0.0
    tls:
      enabled: false
    monitoring:
      enabled: true
      jvm: false
      extended: false
      prometheus:
        enabled: true
        bind: 0.0.0.0
        port: {{ .Values.metrics.port }}
        path: /metrics
    {{- if .Values.config.redis.enabled }}
    cache:
      redis:
        enabled: true
        host: {{ .Values.config.redis.host }}
        port: {{ .Values.config.redis.port }}
        db: 0
    {{- end }}
    {{- if .Values.config.auth.enabled }}
    auth:
      enabled: true
      publicKeyOwner: {{ .Values.config.auth.publicKeyOwner }}
      server:
        keys:
          provider-private-key: /etc/dshackle/auth/private-{{ .Values.config.auth.providerName }}.p8.key
          external-public-key: /etc/dshackle/auth/public-{{ .Values.config.auth.publicKeyOwner }}.pem
    {{- end }}
    proxy:
      host: 0.0.0.0
      port: {{ .Values.service.rpcPort }}
      routes:
      {{- range .Values.config.networks }}
        - id: {{ .id | replace "-" ""}}
          blockchain: {{ .chain }}
      {{- end }}

    cluster:
      upstreams:
        {{- range $key, $network := .Values.config.networks }}
        {{- range $network.upstreams }}
        - id: {{ .id }}
          chain: {{ $network.chain }}
          {{- with $network.options }}
          options:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          connection:
            {{- toYaml .connection | nindent 12 }}
          methods:
            enabled:
              - name: debug_traceBlockByHash
              - name: debug_traceBlockByNumber
              - name: debug_traceCall
              - name: debug_traceTransaction
              - name: trace_block
              - name: trace_replayBlockTransactions
              - name: txpool_content
        {{- end }}
        {{- end }}
