{{- if .Values.config.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dshackle.fullname" . }}-auth
  labels:
    {{- include "dshackle.labels" . | nindent 4 }}
type: Opaque
data:
  private-{{ .Values.config.auth.providerName }}.p8.key: {{ .Values.config.auth.keys.private }}
  public-{{ .Values.config.auth.providerName }}.pem: {{ .Values.config.auth.keys.public }}
  public-{{ .Values.config.auth.publicKeyOwner }}.pem: {{ .Values.config.auth.keys.external }}
{{- end }}
