apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tac-operation-lifecycle.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tac-operation-lifecycle.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}